spring.application.name=bike_example_demo
server.port=8086


# R2DBC Configuration for MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3306/bike_rental_db?sslMode=DISABLED
spring.r2dbc.username=root
spring.r2dbc.password=Admin@123
spring.r2dbc.pool.enabled=true


#
spring.security.user.name=admin
spring.security.user.password=Admin@123

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

# Security JWT Secret Key
security.jwt.secret=mysecretkey123

# SQL Initialization
spring.sql.init.mode=always

# SQL Actuator
